FROM ghcr.io/open-webui/open-webui:0.6.1


ENV SPACE_ID="your-space-id"

ENV ADMIN_USER_EMAIL="admin@admin.com"
ENV ADMIN_USER_PASSWORD="123456"

RUN echo "wmctf{AI_is_the_future}" > /flag

EXPOSE 8080

CMD ["./start.sh"]